# fly.toml app configuration file generated for cinema-memory-next on 2023-05-24T21:57:45-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "cinema-memory-next"
primary_region = "eze"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
