# Generated by Django 4.2 on 2023-05-20 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0004_movie_directors_movie_genres_movie_runtime"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="image",
            field=models.FileField(default="images/default.png", upload_to="images"),
        ),
    ]
